# Generated by Django 3.0.5 on 2020-04-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_imagen'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='productos',
            field=models.ManyToManyField(blank=True, to='productos.Producto'),
        ),
    ]
