# Generated by Django 3.0.5 on 2020-06-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0002_auto_20200608_0543'),
        ('orders', '0004_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billig_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_profiles.BillingProfile'),
        ),
    ]
