# Generated by Django 3.0.5 on 2020-06-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_billig_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billig_profile',
            new_name='billing_profile',
        ),
    ]
