# Generated by Django 3.0.5 on 2020-06-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='card_id',
            field=models.CharField(max_length=100),
        ),
    ]
