# Generated by Django 3.0.5 on 2020-05-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_imagen'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productos',
            field=models.ManyToManyField(through='carts.CartProductos', to='productos.Producto'),
        ),
    ]
